"use client"

import React, { useState, useTransition } from "react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import {
  Sparkles,
  CheckCircle2,
  AlertCircle,
  ChevronRight,
  BookOpen,
  Target,
  TrendingUp,
  RefreshCw,
  Loader2,
  LightbulbIcon,
  ListChecks
} from "lucide-react"
import { generatePerformanceFeedback } from "@/app/actions/ai-feedback"
import type { AIPerformanceFeedback } from "@/lib/ai/types"

interface AIFeedbackPanelProps {
  resultId: string
  initialFeedback: AIPerformanceFeedback | null
}

export function AIFeedbackPanel({ resultId, initialFeedback }: AIFeedbackPanelProps) {
  const [feedback, setFeedback] = useState<AIPerformanceFeedback | null>(initialFeedback)
  const [error, setError] = useState<string | null>(null)
  const [isPending, startTransition] = useTransition()

  const handleGenerate = (forceRegenerate = false) => {
    setError(null)
    startTransition(async () => {
      const res = await generatePerformanceFeedback(resultId, forceRegenerate)
      if (res.success && res.feedback) {
        setFeedback(res.feedback)
      } else {
        setError(res.error || "AI feedback generation failed. Please try again.")
      }
    })
  }

  // No feedback yet — show Generate button
  if (!feedback) {
    return (
      <Card className="shadow-sm border-slate-200 dark:border-slate-800">
        <CardHeader>
          <div className="flex items-center space-x-2">
            <Sparkles className="w-5 h-5 text-violet-500" />
            <CardTitle className="text-lg">AI Performance Insights</CardTitle>
          </div>
          <CardDescription>
            Generate personalized AI feedback based on your performance in this assessment.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {error && (
            <div className="flex items-start space-x-2 text-sm text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-950/60 p-3 rounded-lg border border-red-200 dark:border-red-900">
              <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
              <div>
                <p className="font-medium">AI feedback is temporarily unavailable.</p>
                <p className="text-xs mt-0.5 text-red-500">{error}</p>
              </div>
            </div>
          )}

          {isPending ? (
            <div className="flex flex-col items-center justify-center py-10 space-y-3 text-slate-500">
              <Loader2 className="w-8 h-8 animate-spin text-violet-500" />
              <p className="text-sm font-medium">Generating your performance insights...</p>
              <p className="text-xs text-slate-400">This may take a few seconds</p>
            </div>
          ) : (
            <Button
              onClick={() => handleGenerate(false)}
              disabled={isPending}
              className="w-full bg-violet-600 hover:bg-violet-700 text-white shadow-sm"
            >
              <Sparkles className="w-4 h-4 mr-2" />
              Generate AI Feedback
            </Button>
          )}
        </CardContent>
      </Card>
    )
  }

  // Feedback exists — display it
  return (
    <Card className="shadow-sm border-violet-200 dark:border-violet-900/50 bg-gradient-to-b from-violet-50/50 to-white dark:from-violet-950/20 dark:to-slate-900">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <Sparkles className="w-5 h-5 text-violet-500" />
            <CardTitle className="text-lg">AI Performance Insights</CardTitle>
          </div>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => handleGenerate(true)}
            disabled={isPending}
            className="text-xs text-slate-500 hover:text-violet-700 dark:hover:text-violet-300"
          >
            {isPending ? (
              <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />
            ) : (
              <RefreshCw className="w-3.5 h-3.5 mr-1.5" />
            )}
            {isPending ? "Regenerating..." : "Regenerate"}
          </Button>
        </div>
        <CardDescription>
          Personalized analysis generated by AI based on your assessed performance.
        </CardDescription>
      </CardHeader>

      <CardContent className="space-y-6">
        {isPending && (
          <div className="flex items-center space-x-2 text-sm text-violet-600 dark:text-violet-400 bg-violet-50 dark:bg-violet-950/60 p-3 rounded-lg">
            <Loader2 className="w-4 h-4 animate-spin shrink-0" />
            <span>Regenerating your insights...</span>
          </div>
        )}

        {error && (
          <div className="flex items-start space-x-2 text-sm text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-950/60 p-3 rounded-lg border border-red-200 dark:border-red-900">
            <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
            <div>
              <p className="font-medium">Regeneration failed. Your previous feedback is shown below.</p>
              <p className="text-xs mt-0.5 text-red-500">{error}</p>
            </div>
          </div>
        )}

        {/* Overall Summary */}
        <div className="bg-white dark:bg-slate-900 rounded-xl p-4 border border-slate-200 dark:border-slate-800">
          <div className="flex items-center space-x-2 mb-2">
            <LightbulbIcon className="w-4 h-4 text-amber-500 shrink-0" />
            <span className="text-sm font-semibold text-slate-700 dark:text-slate-200">Overall Summary</span>
          </div>
          <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{feedback.summary}</p>
        </div>

        {/* Strengths */}
        {feedback.strengths.length > 0 && (
          <div className="space-y-2">
            <div className="flex items-center space-x-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
              <span className="text-sm font-semibold text-slate-700 dark:text-slate-200">Strengths</span>
            </div>
            <div className="space-y-1.5 pl-6">
              {feedback.strengths.map((strength, idx) => (
                <div
                  key={idx}
                  className="flex items-start space-x-2 text-sm text-slate-700 dark:text-slate-300"
                >
                  <ChevronRight className="w-3.5 h-3.5 mt-0.5 text-emerald-500 shrink-0" />
                  <span>{strength}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Improvement Areas */}
        {feedback.improvementAreas.length > 0 && (
          <div className="space-y-2">
            <div className="flex items-center space-x-2">
              <Target className="w-4 h-4 text-amber-500 shrink-0" />
              <span className="text-sm font-semibold text-slate-700 dark:text-slate-200">Areas to Improve</span>
            </div>
            <div className="space-y-3 pl-6">
              {feedback.improvementAreas.map((area, idx) => (
                <div key={idx} className="space-y-1">
                  <div className="flex items-center space-x-1.5">
                    <span className="inline-block w-2 h-2 rounded-full bg-amber-400 shrink-0" />
                    <span className="text-sm font-medium text-slate-800 dark:text-slate-200">{area.topic}</span>
                  </div>
                  <p className="text-xs text-slate-600 dark:text-slate-400 ml-3.5 leading-relaxed">
                    {area.explanation}
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Recommendations */}
        {feedback.recommendations.length > 0 && (
          <div className="space-y-2">
            <div className="flex items-center space-x-2">
              <TrendingUp className="w-4 h-4 text-sky-500 shrink-0" />
              <span className="text-sm font-semibold text-slate-700 dark:text-slate-200">Recommended Focus</span>
            </div>
            <div className="space-y-2 pl-6">
              {feedback.recommendations.map((rec, idx) => (
                <div
                  key={idx}
                  className="bg-sky-50 dark:bg-sky-950/40 border border-sky-100 dark:border-sky-900/50 rounded-lg p-3 space-y-1"
                >
                  <p className="text-xs font-semibold text-sky-800 dark:text-sky-300">{idx + 1}. {rec.topic}</p>
                  <p className="text-xs text-sky-700 dark:text-sky-400 leading-relaxed">{rec.reason}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Study Plan */}
        {feedback.studyPlan.length > 0 && (
          <div className="space-y-2">
            <div className="flex items-center space-x-2">
              <ListChecks className="w-4 h-4 text-violet-500 shrink-0" />
              <span className="text-sm font-semibold text-slate-700 dark:text-slate-200">Study Plan</span>
            </div>
            <div className="space-y-3 pl-6">
              {feedback.studyPlan.map((item, idx) => (
                <div key={idx} className="border-l-2 border-violet-200 dark:border-violet-800 pl-3 space-y-1">
                  <p className="text-xs font-semibold text-violet-700 dark:text-violet-300">
                    <BookOpen className="w-3 h-3 inline mr-1" />
                    {item.topic}
                  </p>
                  <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">→ {item.action}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Disclaimer */}
        <p className="text-[11px] text-slate-400 dark:text-slate-600 border-t border-slate-100 dark:border-slate-800 pt-3">
          AI insights are supplementary and for guidance only. Your official score and topic performance shown above are the authoritative record.
        </p>
      </CardContent>
    </Card>
  )
}
